-- Star-schema dimension: physical location (one row per ERA5 grid cell).
--
-- location_id is Postgres-assigned (IDENTITY) so existing IDs survive
-- reloads. The loader upserts on the (region, lat, lon) natural key, which
-- keeps the FK from predictions.location_id stable across DAG runs.

DROP TABLE IF EXISTS dim_location CASCADE;

CREATE TABLE dim_location (
    location_id  INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region       TEXT             NOT NULL,
    lat          DOUBLE PRECISION NOT NULL,
    lon          DOUBLE PRECISION NOT NULL,
    elevation    DOUBLE PRECISION,
    UNIQUE (region, lat, lon)
);

CREATE INDEX idx_dim_location_region ON dim_location (region);
